#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/php-fpm
- name: Inclusion de variables
  ansible.builtin.include_vars:
    file: debian.yml
  when: ansible_facts.os_family == 'Debian'

- name: Inclusion de variables
  ansible.builtin.include_vars:
    file: redhat.yml
  when: ansible_facts.os_family == 'RedHat'

- name: Installation de PHP-FPM
  ansible.builtin.package:
    name: "{{ php_package_name }}"

- name: Configuration du service php-fpm
  ansible.builtin.systemd:
    name: "{{ php_service_name }}"
    state: started
    enabled: true

- name: Template de la conf PHP
  ansible.builtin.template:
    src: php/www.conf
    dest: /etc/php-fpm.d/www.conf
  notify: restart_php
