---
- name: Installation de Redis sur Fedora
  hosts: fedora-cli
  gather_facts: false
  become: true

  tasks:
    - name: Installation
      ansible.builtin.package:
        name: redis
        update_cache: true

    - name: Configuration du service
      ansible.builtin.systemd:
        name: redis
        state: started
        enabled: true

    - name: Configuration Interface d'écoute
      ansible.builtin.lineinfile:
        dest: /etc/redis/redis.conf
        regex: ^bind
        line: bind 192.168.56.246
        backup: true
      notify:
        - restart-redis

    - name: Tâche bidon
      ansible.builtin.debug:
        msg: "Tâche bidon"

  handlers:
    - name: Redémarrage du service Redis
      ansible.builtin.systemd:
        name: redis
        state: restarted
      listen:
        - restart-redis
