---
- name: Installation de Redis sur Fedora
  hosts: fedora-cli
  gather_facts: false
  become: true

  tasks:
    - name: Chargement des variables
      ansible.builtin.include_vars:
        file: redis-conf.yml
      tags: var

    - name: Affichage de la variable redis
      ansible.builtin.debug:
        msg: "variable redis: {{ redis }}"
        verbosity: 1
      tags: var

    - name: Installation
      ansible.builtin.package:
        name: redis
        update_cache: true

    - name: Configuration du service
      ansible.builtin.systemd:
        name: redis
        state: started
        enabled: true

    - name: Configuration Interface d'écoute
      ansible.builtin.lineinfile:
        dest: /etc/redis/redis.conf
        regex: ^bind
        line: "bind {{ if_redis }}"
        backup: true
      notify:
        - restart-redis

    - name: On force l'exécution des handlers jusqu'ici notifiés
      ansible.builtin.meta: flush_handlers

    - name: Tâche bidon
      ansible.builtin.debug:
        msg: "Tâche bidon"

  handlers:
    - name: Redémarrage du service Redis
      ansible.builtin.systemd:
        name: redis
        state: restarted
      listen:
        - restart-redis
