---
- name: Clauses when
  hosts: all

  tasks:
    - name: Affichage des versions majeure et mineure de la distribution
      block:
        - name: Afficher la version de la distribution dans le cas de Debian
          ansible.builtin.debug:
            msg: "Distribution: {{ ansible_distribution_major_version }}"

        - name: Afficher la version de la distribution dans le cas de Debian
          ansible.builtin.debug:
            msg: "Distribution: {{ ansible_distribution_minor_version }}"
      when:
        - ansible_os_family | lower != "redhat" or status | default("nogo") == 'go'

    - name: Démo changed_when
      ansible.builtin.shell:
        cmd: date
      changed_when: false

    - name: Démo n°2 changed_when
      ansible.builtin.shell:
        cmd: grep curt /etc/passwd
      changed_when: false
      register: result
      failed_when: result.rc == 2

    - name: Tâche bidon
      ansible.builtin.debug:
        msg: "Résultat: {{ result }}"

    - name: Clause block...when..rescue..always
      block:
        - name: Test /etc/passwd
          ansible.builtin.shell:
            cmd: grep curt /etc/passwd
      rescue:
        - name: Sauvetage
          ansible.builtin.debug:
            msg: "C'est un peu raté !"
      always:
        - name: Un dernier mot à dire
          ansible.builtin.debug:
            msg: "C'est fini !"
      tags: rescue
