---
- name: Présentation des boucles
  hosts: deby-cli

  tasks:
    - name: Boucle n°1
      ansible.builtin.debug:
        msg: "{{ stagiaire }}"
      loop:
        - Bob
        - Curt
        - Pat
        - Loé
      loop_control:
        loop_var: stagiaire
